"""Drizzle ORM Schema Generator for TypeScript."""

from __future__ import annotations

from backend_ide.domain.schema.models import DatabaseSchema, Table
from backend_ide.generators.contracts import (
    CodeGenerator,
    GeneratedFile,
    GeneratedProject,
    GenerationRequest,
    GenerationTarget,
    GeneratorCategory,
    Language,
    filter_tables,
)
from backend_ide.generators.naming import (
    sanitize_identifier,
    table_to_class_name,
    to_camel_case,
)
from backend_ide.generators.type_mappers.typescript_types import TypeScriptTypeMapper


class DrizzleGenerator(CodeGenerator):
    """Generates TypeScript Drizzle ORM schemas and type inferences."""

    target = GenerationTarget.DRIZZLE
    name = "Drizzle ORM"
    language = Language.TYPESCRIPT
    category = GeneratorCategory.ORM_MODEL
    description = "Modern TypeScript Drizzle ORM schemas and inferred types"

    def generate_table(
        self,
        table: Table,
        schema: DatabaseSchema | None = None,
        request: GenerationRequest | None = None,
    ) -> str:
        """Generate a single Drizzle table definition."""
        var_name = to_camel_case(table.name)
        type_name = table_to_class_name(table.name)

        lines: list[str] = [
            f'export const {var_name} = pgTable("{table.name}", {{',
        ]

        for col in table.columns:
            field_name = sanitize_identifier(col.name, Language.TYPESCRIPT)
            drizzle_builder = TypeScriptTypeMapper.to_drizzle_column(col)
            lines.append(f"  {field_name}: {drizzle_builder},")

        lines.append("});")
        lines.append("")
        lines.append(f"export type {type_name} = typeof {var_name}.$inferSelect;")
        lines.append(f"export type New{type_name} = typeof {var_name}.$inferInsert;")

        return "\n".join(lines)

    def generate(
        self,
        schema: DatabaseSchema,
        request: GenerationRequest,
    ) -> GeneratedProject:
        """Generate complete Drizzle schema TypeScript module."""
        tables_to_generate = filter_tables(schema, request)

        header_lines = [
            "/**",
            " * Drizzle ORM Schema generated by Backend Development IDE",
            " */",
            "",
            "import {",
            "  pgTable,",
            "  serial,",
            "  smallserial,",
            "  bigserial,",
            "  integer,",
            "  smallint,",
            "  bigint,",
            "  varchar,",
            "  char,",
            "  text,",
            "  boolean,",
            "  timestamp,",
            "  date,",
            "  decimal,",
            "  uuid,",
            "  jsonb,",
            '} from "drizzle-orm/pg-core";',
            "",
        ]

        table_blocks: list[str] = []
        for table in tables_to_generate:
            table_blocks.append(self.generate_table(table, schema, request))

        content = "\n".join(header_lines) + "\n\n" + "\n\n".join(table_blocks) + "\n"

        file = GeneratedFile(
            path="schema.ts",
            content=content,
            language=Language.TYPESCRIPT,
        )

        return GeneratedProject(
            target=self.target,
            files=[file],
            metadata={"table_count": len(tables_to_generate)},
        )
