"""Prisma Schema Generator for TypeScript / Node.js."""

from __future__ import annotations

from backend_ide.domain.schema.models import DatabaseSchema, Table
from backend_ide.generators.contracts import (
    CodeGenerator,
    GeneratedFile,
    GeneratedProject,
    GenerationRequest,
    GenerationTarget,
    GeneratorCategory,
    Language,
    filter_tables,
)
from backend_ide.generators.naming import (
    singularize,
    table_to_class_name,
    to_camel_case,
)
from backend_ide.generators.type_mappers.typescript_types import TypeScriptTypeMapper


class PrismaGenerator(CodeGenerator):
    """Generates schema.prisma models from the Universal Schema Model."""

    target = GenerationTarget.PRISMA
    name = "Prisma ORM"
    language = Language.TYPESCRIPT
    category = GeneratorCategory.ORM_MODEL
    description = "Type-safe Prisma ORM schema models (schema.prisma)"

    def generate_table(
        self,
        table: Table,
        schema: DatabaseSchema | None = None,
        request: GenerationRequest | None = None,
    ) -> str:
        """Generate a single Prisma model block."""
        model_name = table_to_class_name(table.name)
        lines: list[str] = [
            f"model {model_name} {{",
        ]

        # Track FK fields
        fk_map: dict[str, tuple[str, str, str]] = {}
        for fk in table.foreign_keys:
            for mapping in fk.column_mappings:
                fk_map[mapping.source_column] = (
                    table_to_class_name(fk.target_table),
                    to_camel_case(singularize(fk.target_table)),
                    mapping.target_column,
                )

        for col in table.columns:
            field_name = to_camel_case(col.name)
            prisma_type = TypeScriptTypeMapper.to_prisma_type(col)

            attributes: list[str] = []
            if col.is_primary_key:
                attributes.append("@id")
                if col.is_auto_increment:
                    attributes.append("@default(autoincrement())")

            if col.default_value and not col.is_auto_increment:
                val = col.default_value.lower()
                if val in ("now()", "current_timestamp"):
                    attributes.append("@default(now())")
                elif val in ("true", "false"):
                    attributes.append(f"@default({val})")
                elif val.isdigit():
                    attributes.append(f"@default({val})")

            # Column mapping if camelCase differs from DB column name
            if field_name != col.name:
                attributes.append(f'@map("{col.name}")')

            attr_str = f" {' '.join(attributes)}" if attributes else ""
            lines.append(f"  {field_name:<16} {prisma_type}{attr_str}")

            # If foreign key, add relation field
            if col.name in fk_map and request and request.include_relationships:
                target_model, rel_field, target_pk = fk_map[col.name]
                lines.append(
                    f"  {rel_field:<16} {target_model} @relation("
                    f"fields: [{field_name}], references: [{to_camel_case(target_pk)}])"
                )

        # Unique constraints
        for uc in table.unique_constraints:
            fields = ", ".join(to_camel_case(c) for c in uc.column_names)
            lines.append(f"  @@unique([{fields}])")

        # Indexes
        for idx in table.indexes:
            if not idx.is_unique:
                fields = ", ".join(to_camel_case(c) for c in idx.columns)
                lines.append(f"  @@index([{fields}])")

        # Table map
        lines.append(f'  @@map("{table.name}")')
        lines.append("}")

        return "\n".join(lines)

    def generate(
        self,
        schema: DatabaseSchema,
        request: GenerationRequest,
    ) -> GeneratedProject:
        """Generate complete schema.prisma file."""
        tables_to_generate = filter_tables(schema, request)

        engine_provider = "postgresql"
        if schema.engine_name in ("mysql", "mariadb"):
            engine_provider = "mysql"
        elif schema.engine_name == "sqlite":
            engine_provider = "sqlite"
        elif schema.engine_name in ("sqlserver", "mssql"):
            engine_provider = "sqlserver"

        header_lines = [
            "// Prisma Schema generated by Backend Development IDE",
            "",
            "generator client {",
            '  provider = "prisma-client-js"',
            "}",
            "",
            "datasource db {",
            f'  provider = "{engine_provider}"',
            '  url      = env("DATABASE_URL")',
            "}",
            "",
        ]

        model_blocks: list[str] = []
        for table in tables_to_generate:
            model_blocks.append(self.generate_table(table, schema, request))

        content = "\n".join(header_lines) + "\n\n" + "\n\n".join(model_blocks) + "\n"

        file = GeneratedFile(
            path="schema.prisma",
            content=content,
            language=Language.TYPESCRIPT,
        )

        return GeneratedProject(
            target=self.target,
            files=[file],
            metadata={"table_count": len(tables_to_generate)},
        )
