"""Universal Schema Model Domain Package."""

from backend_ide.domain.schema.enums import (
    ForeignKeyAction,
    IndexType,
    NormalizedDataType,
    RoutineType,
)
from backend_ide.domain.schema.models import (
    CheckConstraint,
    Column,
    DatabaseSchema,
    ForeignKey,
    ForeignKeyColumnMapping,
    Function,
    Index,
    PrimaryKey,
    Procedure,
    Relationship,
    RoutineParameter,
    Schema,
    Sequence,
    Table,
    Trigger,
    UniqueConstraint,
    View,
)
from backend_ide.domain.schema.serialization import (
    schema_from_dict,
    schema_from_json,
    schema_to_dict,
    schema_to_json,
)

__all__ = [
    "NormalizedDataType",
    "ForeignKeyAction",
    "IndexType",
    "RoutineType",
    "Column",
    "PrimaryKey",
    "ForeignKeyColumnMapping",
    "ForeignKey",
    "Index",
    "UniqueConstraint",
    "CheckConstraint",
    "Sequence",
    "View",
    "Trigger",
    "RoutineParameter",
    "Function",
    "Procedure",
    "Relationship",
    "Table",
    "Schema",
    "DatabaseSchema",
    "schema_to_dict",
    "schema_from_dict",
    "schema_to_json",
    "schema_from_json",
]
