"""Exporters for converting Universal DatabaseSchema into Mermaid.js, DBML, and PlantUML."""

from __future__ import annotations

import re
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from backend_ide.domain.schema.models import DatabaseSchema, Table


class ERMermaidExporter:
    """Generates standard Mermaid.js ER diagram code (erDiagram)."""

    @classmethod
    def export(cls, schema: DatabaseSchema) -> str:
        """Convert DatabaseSchema to Mermaid erDiagram syntax."""
        lines: list[str] = ["erDiagram"]

        all_tables: list[Table] = [t for s in schema.schemas for t in s.tables]
        table_names = {t.name for t in all_tables}

        # 1. Export Relationships
        # Syntax: TABLE_A ||--o{ TABLE_B : "foreign_key"
        seen_relationships = set()
        for table in all_tables:
            for fk in table.foreign_keys:
                if fk.target_table in table_names:
                    rel_key = f"{fk.target_table}_{table.name}_{fk.name}"
                    if rel_key not in seen_relationships:
                        seen_relationships.add(rel_key)
                        label = (
                            fk.column_mappings[0].source_column
                            if fk.column_mappings
                            else "references"
                        )
                        lines.append(f'    {fk.target_table} ||--o{{ {table.name} : "{label}"')

        # 2. Export Table Entities and Fields
        for table in all_tables:
            lines.append(f"    {cls._sanitize_name(table.name)} {{")
            fk_cols = {m.source_column for fk in table.foreign_keys for m in fk.column_mappings}
            pk_cols = set(table.primary_key.column_names) if table.primary_key else set()

            if not table.columns:
                lines.append("        string id PK")
            else:
                for col in table.columns:
                    type_str = cls._clean_type(col.native_type)
                    flags: list[str] = []
                    if col.name in pk_cols or col.is_primary_key:
                        flags.append("PK")
                    if col.name in fk_cols:
                        flags.append("FK")

                    flag_str = " " + " ".join(flags) if flags else ""
                    lines.append(f"        {type_str} {cls._sanitize_name(col.name)}{flag_str}")

            lines.append("    }")

        return "\n".join(lines)

    @staticmethod
    def _sanitize_name(name: str) -> str:
        """Sanitize identifiers to be Mermaid-safe."""
        return re.sub(r"[^a-zA-Z0-9_]", "_", name)

    @staticmethod
    def _clean_type(native_type: str) -> str:
        """Clean type name for Mermaid syntax."""
        cleaned = re.sub(r"\(.*\)", "", native_type).strip().lower()
        cleaned = re.sub(r"[^a-zA-Z0-9_]", "_", cleaned)
        return cleaned or "string"


class ERDbmLExporter:
    """Generates DBML (Database Markup Language) syntax."""

    @classmethod
    def export(cls, schema: DatabaseSchema) -> str:
        """Convert DatabaseSchema to DBML syntax."""
        lines: list[str] = [
            f"// DBML Diagram for {schema.database_name or 'database'}",
            "// Generated by Backend IDE",
            "",
        ]

        all_tables: list[Table] = [t for s in schema.schemas for t in s.tables]
        table_names = {t.name for t in all_tables}

        # 1. Export Tables
        for table in all_tables:
            lines.append(f"Table {table.name} {{")
            pk_cols = set(table.primary_key.column_names) if table.primary_key else set()

            for col in table.columns:
                props: list[str] = []
                if col.name in pk_cols or col.is_primary_key:
                    props.append("pk")
                if col.is_auto_increment:
                    props.append("increment")
                if not col.is_nullable:
                    props.append("not null")
                if col.default_value is not None:
                    props.append(f"default: `{col.default_value}`")

                prop_str = f" [{', '.join(props)}]" if props else ""
                lines.append(f"  {col.name} {col.native_type.lower()}{prop_str}")

            lines.append("}\n")

        # 2. Export References
        for table in all_tables:
            for fk in table.foreign_keys:
                if fk.target_table in table_names:
                    for m in fk.column_mappings:
                        ref_line = (
                            f"Ref: {table.name}.{m.source_column} > "
                            f"{fk.target_table}.{m.target_column}"
                        )
                        lines.append(ref_line)

        return "\n".join(lines)


class ERPlantUMLExporter:
    """Generates PlantUML Entity-Relationship diagram syntax."""

    @classmethod
    def export(cls, schema: DatabaseSchema) -> str:
        """Convert DatabaseSchema to PlantUML ER syntax."""
        lines: list[str] = [
            "@startuml",
            "!theme plain",
            "skinparam linetype ortho",
            "",
        ]

        all_tables: list[Table] = [t for s in schema.schemas for t in s.tables]
        table_names = {t.name for t in all_tables}

        # 1. Entities
        for table in all_tables:
            lines.append(f'entity "{table.name}" as {table.name} {{')
            pk_cols = set(table.primary_key.column_names) if table.primary_key else set()
            fk_cols = {m.source_column for fk in table.foreign_keys for m in fk.column_mappings}

            for col in table.columns:
                prefix = "+"
                if col.name in pk_cols or col.is_primary_key:
                    prefix = "*"
                elif col.name in fk_cols:
                    prefix = "#"

                lines.append(f"  {prefix} {col.name} : {col.native_type}")

            lines.append("}\n")

        # 2. Relationships
        for table in all_tables:
            for fk in table.foreign_keys:
                if fk.target_table in table_names:
                    lines.append(f'{fk.target_table} ||--o{{ {table.name} : "{fk.name}"')

        lines.append("")
        lines.append("@enduml")
        return "\n".join(lines)
