"""Engine for Comparing Database Schemas and Generating DDL Migration Scripts."""

from __future__ import annotations

from typing import TYPE_CHECKING

from backend_ide.domain.diff.models import (
    ColumnDiff,
    SchemaDiffResult,
    TableDiff,
)
from backend_ide.domain.schema.models import Column, DatabaseSchema, Table

if TYPE_CHECKING:
    pass


class SchemaDiffEngine:
    """Compares two DatabaseSchemas and generates structural differences and migration DDL."""

    @classmethod
    def compare(
        cls,
        source: DatabaseSchema,  # Base / Current DB
        target: DatabaseSchema,  # Target / Desired DB
    ) -> SchemaDiffResult:
        """Calculate differences needed to transform source schema into target schema."""
        src_tables: dict[str, Table] = {t.name.lower(): t for s in source.schemas for t in s.tables}
        tgt_tables: dict[str, Table] = {t.name.lower(): t for s in target.schemas for t in s.tables}

        added_tables: list[Table] = []
        dropped_tables: list[Table] = []
        modified_tables: list[TableDiff] = []

        # Find added tables (in target but not source)
        for t_name, tgt_tbl in tgt_tables.items():
            if t_name not in src_tables:
                added_tables.append(tgt_tbl)

        # Find dropped tables (in source but not target)
        for t_name, src_tbl in src_tables.items():
            if t_name not in tgt_tables:
                dropped_tables.append(src_tbl)

        # Compare common tables
        for t_name, tgt_tbl in tgt_tables.items():
            if t_name in src_tables:
                src_tbl = src_tables[t_name]
                diff = cls._compare_table(src_tbl, tgt_tbl)
                if diff:
                    modified_tables.append(diff)

        return SchemaDiffResult(
            source_db_name=source.database_name,
            target_db_name=target.database_name,
            added_tables=added_tables,
            dropped_tables=dropped_tables,
            modified_tables=modified_tables,
        )

    @classmethod
    def _compare_table(cls, src_tbl: Table, tgt_tbl: Table) -> TableDiff | None:
        src_cols: dict[str, Column] = {c.name.lower(): c for c in src_tbl.columns}
        tgt_cols: dict[str, Column] = {c.name.lower(): c for c in tgt_tbl.columns}

        added_cols: list[Column] = []
        dropped_cols: list[Column] = []
        modified_cols: list[ColumnDiff] = []

        for c_name, t_col in tgt_cols.items():
            if c_name not in src_cols:
                added_cols.append(t_col)
            else:
                s_col = src_cols[c_name]
                details = []
                if s_col.native_type.lower() != t_col.native_type.lower():
                    details.append(f"Tipo: {s_col.native_type} -> {t_col.native_type}")
                if s_col.is_nullable != t_col.is_nullable:
                    details.append(f"Nullable: {s_col.is_nullable} -> {t_col.is_nullable}")
                if details:
                    modified_cols.append(
                        ColumnDiff(
                            column_name=t_col.name,
                            diff_type="modified",
                            old_column=s_col,
                            new_column=t_col,
                            details=details,
                        )
                    )

        for c_name, s_col in src_cols.items():
            if c_name not in tgt_cols:
                dropped_cols.append(s_col)

        # Check PK change
        src_pk = set(src_tbl.primary_key.column_names) if src_tbl.primary_key else set()
        tgt_pk = set(tgt_tbl.primary_key.column_names) if tgt_tbl.primary_key else set()
        pk_changed = src_pk != tgt_pk

        if added_cols or dropped_cols or modified_cols or pk_changed:
            return TableDiff(
                table_name=tgt_tbl.name,
                schema_name=tgt_tbl.schema_name or "public",
                diff_type="modified",
                added_columns=added_cols,
                dropped_columns=dropped_cols,
                modified_columns=modified_cols,
                pk_changed=pk_changed,
            )

        return None

    @classmethod
    def generate_migration_ddl(
        cls,
        diff: SchemaDiffResult,
        dialect: str = "postgresql",
        safe_mode: bool = True,
    ) -> str:
        """Generate executable SQL DDL migration script to apply diff."""
        lines: list[str] = [
            f"-- Migration Script: {diff.source_db_name} -> {diff.target_db_name}",
            f"-- Dialect: {dialect.upper()}",
            "-- Generated by Backend Development IDE",
            "",
            "BEGIN TRANSACTION;",
            "",
        ]

        # 1. Create added tables
        for tbl in diff.added_tables:
            lines.append(f"-- Create new table: {tbl.name}")
            col_defs: list[str] = []
            for col in tbl.columns:
                null_str = "NULL" if col.is_nullable else "NOT NULL"
                col_defs.append(f"    {col.name} {col.native_type} {null_str}")

            if tbl.primary_key and tbl.primary_key.column_names:
                pk_cols = ", ".join(tbl.primary_key.column_names)
                col_defs.append(f"    PRIMARY KEY ({pk_cols})")

            cols_block = ",\n".join(col_defs)
            lines.append(f"CREATE TABLE {tbl.name} (\n{cols_block}\n);")
            lines.append("")

        # 2. Modify existing tables
        for t_diff in diff.modified_tables:
            lines.append(f"-- Alter table: {t_diff.table_name}")

            # Add columns
            for col in t_diff.added_columns:
                null_str = "NULL" if col.is_nullable else "NOT NULL"
                lines.append(
                    f"ALTER TABLE {t_diff.table_name} "
                    f"ADD COLUMN {col.name} {col.native_type} {null_str};"
                )

            # Modify columns
            for c_diff in t_diff.modified_columns:
                if c_diff.new_column:
                    lines.append(
                        f"ALTER TABLE {t_diff.table_name} "
                        f"ALTER COLUMN {c_diff.column_name} TYPE {c_diff.new_column.native_type};"
                    )

            # Drop columns (commented out if safe_mode)
            for col in t_diff.dropped_columns:
                drop_sql = f"ALTER TABLE {t_diff.table_name} DROP COLUMN {col.name};"
                if safe_mode:
                    lines.append(f"-- [SAFE MODE - UNCOMMENT TO DROP]: {drop_sql}")
                else:
                    lines.append(drop_sql)

            lines.append("")

        # 3. Drop tables
        for tbl in diff.dropped_tables:
            drop_tbl_sql = f"DROP TABLE {tbl.name};"
            if safe_mode:
                lines.append(f"-- [SAFE MODE - UNCOMMENT TO DROP]: {drop_tbl_sql}")
            else:
                lines.append(drop_tbl_sql)

        lines.extend(["", "COMMIT;"])
        return "\n".join(lines)
